class exim {

    package {
        ['exim4', 'mailutils']:
            ensure => 'installed';
        ['postfix', 'sendmil']:
            ensure => 'absent';
    }

    service {
        'exim4':
            ensure  => 'running',
            enable  => 'true',
            require => Package['exim4'];
    }

    file {
        '/etc/exim4/update-exim4.conf.conf':
            content => template('exim/update-exim4.conf.conf.erb'),
            ensure  => 'present',
            require => Package['exim4'];
        '/etc/mailname':
            content => $fqdn,
            ensure  => 'present',
            require => Package['exim4'];
    }

    exec {
        'update-exim4.conf':
             creates => '/var/lib/exim4/config.autogenerated',
             require => [ File['/etc/exim4/update-exim4.conf.conf'], File['/etc/mailname'] ];
    }

}
